server:
  port: 8080
  tomcat:
    threads:
      max: 200
      min-spare: 10
    connection-timeout: 20000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/one_pass_zwq?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zwq12345
    hikari:
      maximum-pool-size: 20
      connection-timeout: 20000
      minimum-idle: 5
      connection-test-query: SELECT 1
mybatis:
    configuration:
        cache-enabled: false
        map-underscore-to-camel-case: true
