server:
  port: 8080
  tomcat:
    threads:
      max: 200
      min-spare: 10
    connection-timeout: 20000
spring:
  redis:
    host: redis
    port: 6379
    password: zwq12345
    timeout: 20000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 5
mybatis:
    configuration:
        cache-enabled: false
        map-underscore-to-camel-case: true
